#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-test_helper
Version  : 0.0.1
Release  : 4
URL      : https://rubygems.org/downloads/test_helper-0.0.1.gem
Source0  : https://rubygems.org/downloads/test_helper-0.0.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc

%description
No detailed description available

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n test_helper-0.0.1
gem spec %{SOURCE0} -l --ruby > rubygem-test_helper.gemspec

%build
gem build rubygem-test_helper.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
test_helper-0.0.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/test_helper-0.0.1.gem
/usr/lib64/ruby/gems/2.3.0/specifications/test_helper-0.0.1.gemspec
